# cargo-release config file
#   See online reference here: https://github.com/crate-ci/cargo-release/blob/HEAD/docs/reference.md

sign-commit = true
sign-tag = true
dev-version = true
dev-version-ext = "next"

tag-name = "v{{version}}"
tag-message = """Release {{crate_name}} version {{version}}

New features

- Added new generator algorithm "Growing Tree"
- Added new generator algorithm "Prim's Algorithm"
- Added support for exporting mazes as SVG

Bugfixes

- Fix a bug in the Recursive Backtracking generator where it would only generate an empty maze if the size of the target maze was 1,1. It now properly generates a maze with only one cell.

Misc

- Added an example binary that uses this library
"""
