# cargo-release config file
#   See online reference here: https://github.com/crate-ci/cargo-release/blob/HEAD/docs/reference.md

sign-commit = true
sign-tag = true
dev-version = true
dev-version-ext = "next"

tag-name = "v{{version}}"
tag-message = """Release {{crate_name}} version {{version}}

** Breaking Changes **

- Signature of `::generate(…)` hase been changed.
  It now returns a `Result` instead of a maze directly. This is a side effect of the fact that all internal calls
  to `unwrap()`, `expect(…)` or `panic!(…)` have been removed.
  Instead, those error cases now properly propagate instead of killing the application.

Misc

- Clippy lints have been enabled, configured and multiple resulting warnings have been fixed.
"""
